### ISSUE TITLE
Move level info to config

### ISSUE THREAD

**Issue by blond** [bem/bem-walk#15]
Now we can specify the object with `path` field and some optional fields: `naming`, `scheme`.

```js
var walk = require('bem-walk'),
    opts = { scheme: 'nested' };

walk([{ path: 'path/to/level', scheme: 'flat' }], opts)
```

This API may be inconvenient for some cases. It is better to describe information on all possible levels, and then use only paths.

```js
var walk = require('bem-walk'),
    config = {
        defaults: { scheme: 'nested' },
        levels: {
            'common.blocks': { scheme: 'flat' },
            'desktop.blocks': { scheme: 'flat' }
        }
    };

walk(['common.blocks', 'desktop.blocks'], config);
```

**Comment by zxqfox** [comment]
I still believe that we need to declare (or load) levels in config or with config.
Probably it's a task for high-level abstraction over walker.
